name: Schedule Dog-box

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        TIMEZONE: Asia/Shanghai
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        DOG_GIST_ID: e85d2e5765110be1d8cfe57f2557a130
        MARKDOWN_FILE: README.md
        DOG_WIDTH: 58
        DOG_FILL_LEN: 91
      run: |
        mvn -B package --file pom.xml
        java -jar target/dog-box-1.0-SNAPSHOT.jar
    - name: Commit and push
      run: |-
        git config --global user.email "admin@lilu.org.cn" && git config --global user.name "sunchaser-lilu"
        git diff
        git add README.md && git commit -m ":robot: Github Action schedule automatically" || exit 0
        git pull --rebase && git push
